--|--------------------------------------------------------------------------------
--| 17. Вставка узла (лист)
--|--------------------------------------------------------------------------------

--| 1 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'B');
-- call AddLeaf('D', 'C');
-- call AddLeaf('E', 'D');
-- call AddLeaf('F', 'E');

--| 2 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'B');
-- call AddLeaf('D', 'C');
-- call AddLeaf('E', 'D');
-- call AddLeaf('F', 'E');
-- call AddLeaf('G', 'F');
-- call AddLeaf('H', 'E');
-- call AddLeaf('J', 'D');

--| 3 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'B');
-- call AddLeaf('D', 'C');
-- call AddLeaf('E', 'D');
-- call AddLeaf('F', 'E');
-- call AddLeaf('G', 'F');
-- call AddLeaf('H', 'E');
-- call AddLeaf('J', 'D');
-- call AddLeaf('K', 'J');
-- call AddLeaf('L', 'J');
-- call AddLeaf('M', 'J');

--|--------------------------------------------------------------------------------
--| 17. Вставка узла
--|--------------------------------------------------------------------------------

--| 1 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- DELETE FROM children;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call AddLeaf('F', 'A');
-- call AddLeaf('D', 'B');
-- call AddLeaf('E', 'B');
-- call AddLeaf('M', 'C');
-- call AddLeaf('N', 'C');
-- call AddLeaf('L', 'C');
-- INSERT INTO children VALUES('B', 2, 7);
-- INSERT INTO children VALUES('C', 8, 15);
-- call InsertNode('Z', 'A');
-- SELECT * FROM nested;

--| 2 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- DELETE FROM children;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call AddLeaf('F', 'A');
-- call AddLeaf('D', 'B');
-- call AddLeaf('E', 'B');
-- call AddLeaf('M', 'C');
-- call AddLeaf('N', 'C');
-- call AddLeaf('L', 'C');
-- INSERT INTO children VALUES('N', 11, 12);
-- call InsertNode('Z', 'C');
-- SELECT * FROM nested;

--|--------------------------------------------------------------------------------
--| 18. Удаление листа (лист)
--|--------------------------------------------------------------------------------

--| 1 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call RemoveLeaf('A'); -- fails
-- call RemoveLeaf('C');

--| 2
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call RemoveLeaf('C');
-- call RemoveLeaf('B');
-- call RemoveLeaf('A');

--| 3 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'B');
-- call AddLeaf('D', 'C');
-- call AddLeaf('E', 'D');
-- call AddLeaf('F', 'E');
-- call AddLeaf('G', 'F');
-- call AddLeaf('H', 'E');
-- call AddLeaf('J', 'D');
-- call AddLeaf('K', 'J');
-- call AddLeaf('L', 'J');
-- call AddLeaf('M', 'J');
-- call RemoveLeaf('G');
-- call RemoveLeaf('L');
-- call RemoveLeaf('M');

--|--------------------------------------------------------------------------------
--| 18. Удаление узла 
--|--------------------------------------------------------------------------------

--| 1 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call AddLeaf('D', 'B');
-- call AddLeaf('E', 'B');
-- call AddLeaf('F', 'C');
-- call AddLeaf('K', 'C');
-- call RemoveNode('B');

--| 2 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call AddLeaf('D', 'B');
-- call AddLeaf('E', 'B');
-- call AddLeaf('F', 'C');
-- call AddLeaf('K', 'C');
-- call RemoveNode('C');

--| 3 
--|--------------------------------------------------------------------------------
-- DELETE FROM nested;
-- call AddLeaf('A');
-- call AddLeaf('B', 'A');
-- call AddLeaf('C', 'A');
-- call AddLeaf('D', 'B');
-- call AddLeaf('E', 'B');
-- call AddLeaf('M', 'D');
-- call AddLeaf('N', 'D');
-- call AddLeaf('F', 'C');
-- call AddLeaf('K', 'C');
-- call RemoveNode('B');