--|--------------------------------------------------------------------------------
--| 1. Добавление вершины
--|--------------------------------------------------------------------------------
-- DELETE FROM Vertice;
-- call AddVertice('A');
-- call AddVertice('B');
-- SELECT * FROM Vertice;

--|--------------------------------------------------------------------------------
--| 2. Удаление вершины
--|--------------------------------------------------------------------------------
-- DELETE FROM Vertice;
-- call AddVertice('A');
-- call AddVertice('B');
-- call AddVertice('C');
-- call AddVertice('D');
-- call RemoveVertice('A');
-- SELECT * FROM Vertice;

--|--------------------------------------------------------------------------------
--| 3. Добавление дуги
--|--------------------------------------------------------------------------------
-- DELETE FROM Vertice;
-- DELETE FROM AdjMatrix;
-- call AddVertice('A');
-- call AddVertice('B');
-- call AddVertice('C');
-- call AddVertice('D');
-- call AddEdge('A', 'B');
-- call AddEdge('B', 'A');
-- call AddEdge('B', 'C');
-- call AddEdge('C', 'D');
-- call ShowMatrix();

--|--------------------------------------------------------------------------------
--| 4. Удаление дуги
--|--------------------------------------------------------------------------------
-- DELETE FROM Vertice;
-- DELETE FROM AdjMatrix;
-- call AddVertice('A');
-- call AddVertice('B');
-- call AddVertice('C');
-- call AddVertice('D');
-- call AddEdge('A', 'B');
-- call AddEdge('B', 'A');
-- call AddEdge('B', 'C');
-- call AddEdge('C', 'D');
-- 
-- call RemoveEdge('C', 'D');
-- call ShowMatrix();
-- 
-- call RemoveVertice('A');
-- call ShowMatrix();

--|--------------------------------------------------------------------------------
--| 5. Определить смежность вершин
--|--------------------------------------------------------------------------------
-- DELETE FROM Vertice;
-- DELETE FROM AdjMatrix;
-- call AddVertice('A');
-- call AddVertice('B');
-- call AddVertice('C');
-- call AddVertice('D');
-- call AddEdge('A', 'B');
-- call AddEdge('B', 'A');
-- call AddEdge('B', 'C');
-- call AddEdge('C', 'D');
-- call CheckAdjacency('A', 'B');
-- call CheckAdjacency('B', 'A');
-- call CheckAdjacency('B', 'C');
-- call CheckAdjacency('C', 'D');
-- call CheckAdjacency('A', 'D');
-- call CheckAdjacency('C', 'B');

--|--------------------------------------------------------------------------------
--| 6. Определить инцидентность узла к ребру
--|--------------------------------------------------------------------------------
-- DELETE FROM Vertice;
-- DELETE FROM AdjMatrix;
-- call AddVertice('A');
-- call AddVertice('B');
-- call AddVertice('C');
-- call AddVertice('D');
-- call AddEdge('A', 'B');
-- call AddEdge('B', 'A');
-- call AddEdge('B', 'C');
-- call AddEdge('C', 'D');
-- select * from AdjMatrix;
-- call CheckIncidence('A', 1);
-- call CheckIncidence('B', 2);
-- call CheckIncidence('C', 3);
-- call CheckIncidence('D', 4);
-- call CheckIncidence('A', 4);
-- call CheckIncidence('B', 4);